name: Build and Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install PortAudio Linux
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y portaudio19-dev python3-dev

    - name: Install PortAudio macOS
      if: matrix.os == 'macos-latest'
      run: brew install portaudio

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build Executable Windows
      if: matrix.os == 'windows-latest'
      run: pyinstaller --onefile --name NoNetVoice-Windows dictation.py

    - name: Build Executable Linux
      if: matrix.os == 'ubuntu-latest'
      run: pyinstaller --onefile --name NoNetVoice-Linux dictation.py

    - name: Build Executable macOS
      if: matrix.os == 'macos-latest'
      run: pyinstaller --onefile --name NoNetVoice-macOS dictation.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: executable-${{ matrix.os }}
        path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist
        merge-multiple: true

    - name: Publish Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: Latest
        name: Latest Build
        files: dist/*